### ISSUE TITLE
LoginRouteArgs can not be null because it has a required parameter

### ISSUE THREAD

**Issue by micheljung** [Chinmay-KB/route_guard_example#2]
When accessing the login route directly, no `onLoginCallback` can be set:

```
Error: LoginRouteArgs can not be null because it has a required parameter
    at Object.throw_ [as throw] (http://localhost:50469/dart_sdk.js:5067:11)
    at routing_controller.RouteData.new.argsAs (http://localhost:50469/packages/auto_route/src/router/widgets/auto_tabs_scaffold.dart.lib.js:4247:21)
    at http://localhost:50469/packages/route_guard_example/screens/login/login_screen.dart.lib.js:1033:30
    at router$46gr.AppRouter.new.[_pageBuilder] (http://localhost:50469/packages/auto_route/src/router/widgets/auto_tabs_scaffold.dart.lib.js:5391:70)
    at router$46gr.AppRouter.new.[_addEntry] (http://localhost:50469/packages/auto_route/src/router/widgets/auto_tabs_scaffold.dart.lib.js:3878:36)
    at router$46gr.AppRouter.new._pushAllGuarded (http://localhost:50469/packages/auto_route/src/router/widgets/auto_tabs_scaffold.dart.lib.js:3862:46)
    at _pushAllGuarded.next (<anonymous>)
    at http://localhost:50469/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:50469/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50469/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:50469/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:50469/dart_sdk.js:35969:17)
    at _Future.new.[_completeWithValue] (http://localhost:50469/dart_sdk.js:35817:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50469/dart_sdk.js:35838:35)
    at Object._microtaskLoop (http://localhost:50469/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:50469/dart_sdk.js:40714:13)
    at http://localhost:50469/dart_sdk.js:36191:9
```

Do you have a solution for this?

**Comment by Chinmay-KB** [comment]
Actually yes I do. Making onLoginCallback nullable works just fine. I faced this issue myself in production and fixed it, forgot about fixing it here, sorry 😬
